title: Technical Resume
author: Andrew Walker
email: andrew-walker@utulsa.edu
description: > # this means to ignore newlines until "baseurl:"

# social links
github_username:  anw984

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-slate
