title: Technical Resume
author: Andrew Walker
email: andrew-walker@utulsa.edu
description: > # this means to ignore newlines until "baseurl:"
  My Name is Andrew Walker and I'm a student at The University of Tulsa. 
  I've spent the last 4 years learning everything relating to the Information Technology industry -- from object-oriented programming, to SQL databases, and cybersecurity. 
  I'm currently applying this knowledge in my role as a Service Center Trainer for QuikTrip Corporation, where I'm responsible for writing knowledge articles, performing initial and ongoing training for analysts, and collaborating with developers to align our processes."
# social links
github_username:  anw984

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-slate
